### ISSUE TITLE
Need better quality pictures of sponsor logos

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#1]

**Comment by Snowboardpvp** [comment]
Yeah, I agree with this. Most of them are kind of decent, but BeastNode's looks dreadful. It is also kind of hard to read some of them in general in front of parts of the background they are placed over.

**Comment by Owexz** [comment]
Fixed as of #9

**Comment by Zidane** [comment]
This isn't fixed as the Nitrous logo was switched to a red one. What is their official logo? They should be contacted and asked about the one they want.

**Comment by Owexz** [comment]
The red version is Nitrous Network's new logo as found across their sites:
https://nitrous-networks.com/
https://twitter.com/nitrousnetworks
https://www.facebook.com/NitrousNetworks

They will be contacted regardless to enquire as to their preference however.

**Comment by MichaelHillcox** [comment]
@Zidane Yeah, I changed it to red because thats the one they are currently using.

**Comment by gabizou** [comment]
I would also request a better quality version of BeastNode's logo as the font used in the current version is not matching what's on their website.

**Comment by Tzky** [comment]
Bump. Is this resolved?

**Comment by gabizou** [comment]
@Tzky what's the latest logos look like?

**Comment by Tzky** [comment]
Yep, noticed that the font is still wrong...

**Comment by progwml6** [comment]
bump again ...

If this is not resolved please list which logos need updating

**Comment by jamierocks** [comment]
Now Nitrous is no longer a sponsor, I believe this issue is resolved.
