### ISSUE TITLE
Adjust navbar to be consistent with Forums/Docs/Ore

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeHome#3]

**Comment by Tzky** [comment]
The navbar should be consitent with the bar on the forums, docs still has minor differences to the forums which i need to sort out.

**Comment by Snowboardpvp** [comment]
@Tzky It does seem consistent in most aspects, but to me there are still some inconsistencies.
- The highlighting when you hover over "Sponge" does not go far enough to the left. I cannot tell exactly, but it does not seem to go far enough to the right either. As a result, the dropdown is not of the right width either.
- The Sponge logo on the navbar, when you have the website at a lower width(such as half a 1080p screen), does not maintain padding to the left of the browser but rather stays touching to it, where as there is some padding always on the forums.(This problem also occurs on the SpongeDocs).
- The arrow shows up as a box in Chrome and nothing in Edge, and has a yellow line underneath it when you hover.
- When you hover over an item in the dropdown they have are underlined unlike elsewhere, and the highlight color is not yellow, but rather a grey.
- Many icons are different in the dropdown: Homepage doesn't match at all, the forum pencils do not match and are different directions, the Code <> shows up as a box in Chrome and nothing in Edge like the arrow, the SpongeDocs icon does not match, the JavaDocs one does but is italicized, the plugin icons are similar but this home page one is italicized and seems a bit smaller, the "Get Sponge" one is italicized as well. There is also a Chat button, but I am assuming that may be later added to the other ones.

**Comment by MichaelHillcox** [comment]
@Snowboardpvp I've fixed all those issues in my #9

**Comment by Zidane** [comment]
@MichaelHillcox 

You've brought the navbar very close to the forums (if not identical, need to check). This is an issue we have across all the web projects and I'm working to unify the navbar across them all.

**Comment by Tzky** [comment]
At least Forums and docs should be consistent for now, spongehome is next :)

**Comment by MichaelHillcox** [comment]
@Zidane Tell me what it is and I'll get it fixed up :)

**Comment by Tzky** [comment]
Bump. I just pushed some changes (bd2f430) to the navbar. It should almost be consistent with the Docs now.

Is this issue resolved now?

EDIT:
Navbar needs some fixing when using a mobile device. Specifically the 3 yellow buttons on the right are broken.

**Comment by progwml6** [comment]
Bump, we have fixed some more issues with the navbar on mobile devices in the last week

Is this issue resolved now?

**Comment by Tzky** [comment]
Mobile issues remain, but that's what #76 is for. I vote for close on this one.

**Comment by JBYoshi** [comment]
The icons still don't match the docs (and what the forums previously had). Looks like those use entypo instead; SpongeHome and Ore use fontawesome.

**Comment by Tzky** [comment]
This is correct and the Docs will get FA too when SpongeHome is ready. So it's not an issue on SpongeHome but rather the Docs and Forums.

issue on the docs theme repo:
SpongePowered/sponge_docs_theme/issues/15

**Comment by Tzky** [comment]
Update: The Docs are using FontAwesome now.

**Comment by MichaelHillcox** [comment]
The fonts bigger on the homepage and docs than it is on the forums ( thats the logos font size ). 
Homepage has padding-right and margin right for the nav container and then the last-child li element. Meaning the items on the right have more space from the edge of the container than they do on spongedocs and forums.

**Comment by jamierocks** [comment]
Unless I'm missing something, this has been completely addressed?
