### ISSUE TITLE
Page is too wide on my mobile device

### ISSUE THREAD

**Issue by mattysweeps** [SpongePowered/SpongeHome#76]
Phone: Samsung Galaxy S6 Edge 

The width of the page is a little too wide for my phone.

http://postimg.org/image/kuajl6rkx/
http://postimg.org/image/4b17hs00x/

**Comment by Tzky** [comment]
We don't have adverts on our site. Can you get rid of them and report back if the issue persists?

**Comment by jamierocks** [comment]
This issue was silently fixed in https://github.com/SpongePowered/SpongeHome/pull/71 :P

**Comment by mbroomfield-r7** [comment]
I'm still seeing the issue. The tab menu in the upper right corner can only be seen if I scroll the browser horizontally. Also, I'm still having the issue with the text (what the pics above show). All of this is because the page is slightly too wide.

**Comment by mbroomfield-r7** [comment]
Also, what do you mean by "adverts"?

**Comment by Tzky** [comment]
Nvm, didn't realise that the ads are on the page you used to upload our Screens. We'll look into it.

**Comment by Tzky** [comment]
I'll close as #71 got pulled. If your issue still persists, please report back and reopen :)

**Comment by Tzky** [comment]
Just tested on my Xperia Z1C. The issue still persists.

**Comment by jamierocks** [comment]
Yes - I only fixed the headings inside the announcements

**Comment by Tzky** [comment]
Fixed with 3391442
